protocol: sftp # or ftp

host: 192.168.1.1
port: 22
username: myuser
password: mypass

remote_path: /var/www/project

workers: 15

ignore:
  - vendor
  - node_modules
  - .git
  - .env
  - "*.log"
